require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'

  config.vm.define 'control' do |km|
    km.vm.network 'private_network', ip: '192.168.33.33'
    km.vm.hostname = 'kubernetes.local'

    km.vm.provider 'virtualbox' do |vb|
      vb.cpus = '4'
      vb.memory = '2048'
    end
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network 'private_network', ip: "192.168.33.3#{i + 3}"
      node.vm.hostname = "kubenode#{i}.local"
      node.vm.synced_folder '.', '/vagrant', disabled: true
    end
  end

  # TODO: this needs to run after all are spun up because the nodes need the registered token from the control
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'bootstrap.yml'
    ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
  end
end
