---
- name: Install git and ansible
  ansible.builtin.apt:
    name:
    - git
    - ansible
    state: present
    update_cache: true # need for universe --> ansible

- name: Retrieve awx version {{ awx_version }}
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    dest: /tmp/awx
    version: "{{ awx_version }}"
    force: true

# template must be verified against file from git repo whenever new version of awx is installed; currently ingress annotations are bugged in awx installer
- name: Configure awx installer inventory file
  ansible.builtin.template:
    src: inventory.j2
    dest: /tmp/awx/installer/inventory
    mode: '0644'

- name: Execute awx installation playbook
  ansible.builtin.command: ansible-playbook -i inventory install.yml
  args:
    chdir: /tmp/awx/installer

- name: Uninstall git and ansible
  ansible.builtin.apt:
    name:
    - git
    - ansible
    state: absent

# inventory: ssl, admin user password, secret key, pg pv on ebs
