require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'
  config.vm.network 'private_network', ip: '192.168.8.8'
  config.vm.hostname = 'microk8s.local'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '4'
    vb.memory = '2048'
  end

  # bootstrap box
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'bootstrap.yml'
    ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
  end
end
