---
- name: bootstrap an ubuntu microk8s worker vagrant box
  hosts: all, localhost
  become: true
  vars_files:
  - vars.yml

  tasks:
  - name: install microk8s snap
    community.general.snap:
      name: microk8s
      state: present
      channel: "{{ kube_version }}/stable"
      classic: true

  - name: start microk8s
    ansible.builtin.command: microk8s.start

  # TODO: obtain command from controller tasks
  #- name: join kubernetes cluster
    #ansible.builtin.command: microk8s join 192.168.8.8:25000/???
