---
- name: Bootstrap an ubuntu microk8s worker vagrant box
  hosts: all, localhost
  become: true
  vars_files:
  - vars.yml

  tasks:
  - name: Install microk8s snap
    community.general.snap:
      name: microk8s
      state: present
      channel: "{{ kube_version }}/stable"
      classic: true

  - name: Start microk8s
    ansible.builtin.command: microk8s.start

  - name: Join kubernetes cluster
    ansible.builtin.command: "{{ lookup('ansible.builtin.file', 'cluster_join' + worker | string) }} --worker"

  - name: Ensure cluster join file no longer exists after use
    ansible.builtin.file:
      path: cluster_join{{ worker | string }}
      state: absent
