require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'
  config.vm.network 'private_network', ip: '192.168.88.88'
  config.vm.hostname = 'kubernetes.local'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '4'
    vb.memory = '2048'
  end

  # bootstrap box
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'bootstrap.yml'
  end
end
