Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'

  config.vm.define 'client' do |client|
    client.vm.network 'private_network', ip: '192.168.210.11'
    client.vm.hostname = 'client.local'
    client.vm.provision 'shell', path: 'base.sh'
  end

  config.vm.define 'server' do |server|
    server.vm.network 'private_network', ip: '192.168.210.10'
    server.vm.hostname = 'server.local'
    server.vm.provision 'shell', path: 'base.sh'
    server.vm.provision 'shell', path: 'server.sh'

    server.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
    end
  end
end
