require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'fedora/26-cloud-base'
  config.vm.hostname = 'jenkins.local'
  config.vm.network 'private_network', ip: '192.168.33.10'
  config.vm.network 'forwarded_port', guest: 8080, host: 80

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '4'
    vb.memory = '2048'
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'provision.yml'
    ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
  end
end

# ssh -p 2222 vagrant@127.0.0.1 sudo java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080 declarative-linter < declarative/Jenkinsfile
