require_relative '../vagrant/vagrant_utilities'

Vagrant.configure('2') do |config|
  config.vm.box = 'fedora/29-cloud-base'
  config.vm.hostname = 'jenkins.local'
  config.vm.network 'private_network', ip: '192.168.33.10'
  config.vm.network 'forwarded_port', guest: 8080, host: 80

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '4'
    vb.memory = '2048'
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'provision.yml'
  end

  config.trigger.after %i[resume reload] do |ntpd_trigger|
    ntpd_trigger.name = 'restart ntpd'
    ntpd_trigger.info = 'Restarting ntpd for Github API usage.'
    ntpd_trigger.run_remote = { inline: 'systemctl restart ntpd' }
  end
end

# ssh -p 2222 vagrant@127.0.0.1 sudo java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080 declarative-linter < declarative/Jenkinsfile
