Vagrant.configure('2') do |config|
  config.vm.box = 'centos/8'
  config.vm.hostname = 'puppet'
  config.vm.network 'private_network', ip: '192.168.12.34'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '4'
    vb.memory = '4096'
  end
end
