# vboxmanage list vms
# vagrant package --base vagrant_master_* --output master.box

# Dependency and config checks
require_relative '../vagrant/vagrant_utilities'

raise 'Missing PE Master tarball.' if Dir.glob('puppet-enterprise-2018-*-el-7-x86_64.tar.gz').empty?

plugins_install(%w[vagrant-pe_build])

# Configure boxes
Vagrant.configure('2') do |config|
  config.pe_build.version = '2018.1.3'
  config.vm.box = 'centos/7'
  config.pe_build.download_root = "file://#{Dir.pwd}"
  config.ssh.insert_key = false
  # TODO: vb sync provider and sync code, puppet, r10k directories?

  config.vm.define 'master' do |pm|
    pm.vm.network 'private_network', ip: '192.168.123.10'
    pm.vm.hostname = 'puppet.local'

    pm.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2560'
    end

    pm.vm.provision 'shell', path: 'base.sh'
    pm.vm.provision 'shell', path: 'master.sh'
    pm.vm.provision :pe_bootstrap do |pe|
      pe.role = :master
    end
    pm.vm.provision 'shell', inline: '/opt/puppetlabs/bin/puppet agent -t; exit 0'
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network 'private_network', ip: "192.168.123.1#{i}"
      node.vm.hostname = "node#{i}"
      node.vm.synced_folder '.', '/vagrant', disabled: true

      node.vm.provision 'shell', path: 'base.sh'
      node.vm.provision :pe_agent do |pe|
        pe.master_vm = 'master'
      end
      node.vm.provision 'shell', inline: 'systemctl disable puppet; systemctl stop puppet'
    end
  end
end
