# Dependency and config checks
require_relative '../vagrant/vagrant_utilities'

# Configure boxes
Vagrant.configure('2') do |config|
  # need to fix nameserver during boot
  config.vm.box = 'debian/stretch64'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = '2'
    vb.memory = '1024'
  end

  config.vm.provision 'shell', path: 'provision.sh'
end
